---
# - name: Apply common configurations to all servers
#   hosts: all
#   become: true
#   roles:
#     - common

# - name: Set up Nginx web server
#   hosts: web
#   become: true
#   roles:
#     - nginx

# - name: Install and configure Docker
#   hosts: app
#   become: true
#   roles:
#     - docker

- name: Deploy application container
  hosts: app
  become: true
  vars_files:
    - ../group_vars/app/main.yml
  roles:
    - app